"use client";
import {useState} from 'react';
import report from '@/data/model-v2.json';
import context from '@/data/context.json';
import schedule from '@/data/schedule.json';
import {projectPlayers,rotationSummary,clamp,type TeamData,type Scenario,type RotationEdit} from '@/lib/model';
const fmt=(n:number,d=1)=>n.toFixed(d);

export function RotationLab({data,scenario,onChange}:{data:TeamData;scenario:Scenario;onChange:(s:Scenario)=>void}){
 const [anchor,setAnchor]=useState('');
 const rows=projectPlayers(data,scenario),summary=rotationSummary(data,scenario);
 const c=context.teams.find(t=>t.id===data.id),options=c?.onoff?.filter(o=>o.rows.length)??[];
 const selected=options.find(o=>o.playerId===anchor)??options[0];
 const update=(id:string,patch:RotationEdit)=>onChange({...scenario,rotation:{...scenario.rotation,[id]:{...scenario.rotation?.[id],...patch}}});
 function absence(){if(!selected)return;const edits={...scenario.rotation,[selected.playerId]:{...scenario.rotation?.[selected.playerId],gp:0}};
  for(const r of selected.rows){if(r.id&&r.on>0){const exposure=Math.min(r.minutesOn,r.minutesOff),weight=exposure/(exposure+500);edits[r.id]={...edits[r.id],usage:Math.round(clamp((r.off/r.on-1)*100*weight,-20,20))};}}
  onChange({...scenario,rotation:edits});
 }
 return <section className="panel rotation-lab"><div className="panel-title"><div><p className="eyebrow">MINUTES → OPPORTUNITY → PRODUCTION</p><h3>Build the rotation</h3></div><button className="text-button" onClick={()=>onChange({...scenario,rotation:{},pace:0})}>Reset rotation</button></div>
 <p className="subtext">Edit minutes when active, games available, and usage. Roles set a starting minute estimate. Projections and the team outlook update together. Edits last for this session and reset when switching teams.</p>
 <div className="rotation-summary"><div><strong>{fmt(summary.used)} / 240</strong><span>Minutes per team game</span></div><div><strong>{fmt(summary.unassigned)}</strong><span>Unassigned / replacement minutes</span></div><div><strong>{fmt(summary.shots)}</strong><span>Estimated FGA per team game</span></div><div><strong>{c?.pace?fmt(c.pace):'—'}</strong><span>Observed pace · possessions / 48</span></div></div>
 <div className="position-budget">{summary.positions.map(p=><span key={p.position}>{p.position}: {fmt(p.minutes)} expected minutes</span>)}</div>
 <p className="footnote">Minutes are weighted by GP ÷ 82. An overfilled rotation scales proportionally to 240. Unassigned minutes stay explicit; rookies without NBA history are not assigned invented production. Multi-position players may appear in more than one position total.</p>
 <label className="pace-control">Pace change from baseline <input aria-label="Pace change percent" type="range" min="-10" max="10" value={scenario.pace??0} onChange={e=>onChange({...scenario,pace:Number(e.target.value)})}/><output>{scenario.pace??0}%</output></label>
 <div className="table-scroll"><table className="rotation-table"><thead><tr><th>PLAYER / ROLE</th><th>MIN WHEN ACTIVE</th><th>GAMES</th><th>USAGE Δ %</th><th>FP / GAME</th><th>FP RANGE*</th><th>GP RANGE*</th></tr></thead><tbody>{rows.filter(p=>p.projection).map(p=>{const s=p.projection!;return <tr key={p.id}><td><b>{p.name}</b><select aria-label={`${p.name} role`} value={s.role} onChange={e=>update(p.id,{role:e.target.value,min:({Starter:32,Rotation:22,Bench:10,Inactive:0} as Record<string,number>)[e.target.value]})}>{['Starter','Rotation','Bench','Inactive'].map(r=><option key={r}>{r}</option>)}</select><small>{p.last?.teamIds.includes(data.id)?'Returning':'New teammate'} · {p.position}</small></td><td><input aria-label={`${p.name} minutes`} type="number" min="0" max="48" step="1" value={Number(s.requestedMin.toFixed(1))} onChange={e=>update(p.id,{min:clamp(Number(e.target.value),0,48)})}/>{s.minuteScale<1&&<small>Effective {fmt(s.min)}</small>}</td><td><input aria-label={`${p.name} games`} type="number" min="0" max="82" value={s.gp} onChange={e=>update(p.id,{gp:clamp(Number(e.target.value),0,82)})}/></td><td><input aria-label={`${p.name} usage change`} type="number" min="-30" max="30" value={s.usage} onChange={e=>update(p.id,{usage:clamp(Number(e.target.value),-30,30)})}/></td><td className="fp">{fmt(s.fp)}</td><td>{fmt(s.fpLow)}–{fmt(s.fpHigh)}</td><td>{s.gpLow}–{s.gpHigh}</td></tr>})}</tbody></table></div>
 <p className="footnote">*Sensitivity ranges informed by historical errors, widened for sparse history and a new team. They are not calibrated confidence intervals or injury predictions. Usage changes scoring, assists, threes, and turnovers; it is an exploratory assumption.</p>
 <div className="onoff"><div className="panel-title"><h3>When a key teammate sits</h3><span className="chip">2025–26 ON / OFF</span></div>{selected?<><div className="absence-controls"><label>Teammate <select aria-label="On off teammate" value={selected.playerId} onChange={e=>setAnchor(e.target.value)}>{options.map(o=><option key={o.playerId} value={o.playerId}>{o.name}</option>)}</select></label><button className="button" onClick={absence}>Apply full-season absence</button></div><p className="method-text">Sets this player to 0 games and applies teammates’ observed off/on usage changes, shrunk by the smaller sample ÷ (sample + 500 minutes), capped at ±20%. Reassign the vacated minutes above. This is a hypothetical scenario, not an injury prediction.</p><div className="table-scroll"><table><thead><tr><th>TEAMMATE</th><th>USAGE ON</th><th>USAGE OFF</th><th>MIN ON / OFF</th></tr></thead><tbody>{selected.rows.map(r=><tr key={r.id}><td>{r.name}</td><td>{fmt(r.on)}%</td><td>{fmt(r.off)}%</td><td>{r.minutesOn} / {r.minutesOff}</td></tr>)}</tbody></table></div><p className="footnote">Association is not causation. Opponents, lineups, roles, and coaching confound on/off differences. <a href={selected.source} target="_blank" rel="noreferrer">View source</a>.</p></>:<p className="method-text">No usable on/off snapshot is available for this team’s selected returning leaders. Use manual usage assumptions above; no on/off effect is invented.</p>}<p className="footnote">PBP Stats snapshot: {context.fetchedAt.slice(0,10)}. Historical context does not refresh with the live ESPN roster button.</p></div>
 </section>;
}

export function BacktestReport(){
 const rows=[{name:'Fantasy points / game · active players',data:report.fantasyReport,scale:1},{name:'Team wins / 82 games',data:report.team.report,scale:1},{name:'Minutes / game · active players',data:report.minutes.report,scale:1},{name:'Games / 82 · current cohort',data:report.games.report,scale:1},...Object.entries(report.rates).map(([k,v])=>({name:`${k.toUpperCase()} per 36 minutes`,data:v.report,scale:36}))];
 return <div className="model-content"><section className="panel"><div className="panel-title"><div><p className="eyebrow">MEASURED AGAINST A SIMPLE BASELINE</p><h3>Does the model actually improve?</h3></div><span className="chip">MODEL V2</span></div><p className="subtext">A time-ordered holdout compares fitted projections with repeating the previous season. Lower error is better. These results evaluate the statistical components, not your edited rotation or the final schedule simulation.</p><div className="split-timeline"><div><b>Train</b><span>2016–2022 outcomes</span></div><div><b>Select parameters</b><span>2023 outcomes</span></div><div><b>Held-out test</b><span>2024–2026 outcomes</span></div></div><div className="table-scroll"><table><thead><tr><th>MEASURE</th><th>TEST CASES</th><th>REPEAT LAST YEAR MAE</th><th>FITTED MAE</th><th>CHANGE</th></tr></thead><tbody>{rows.map(r=><tr key={r.name}><td>{r.name}</td><td>{r.data.n}</td><td>{fmt(r.data.baselineMae*r.scale,2)}</td><td>{fmt(r.data.mae*r.scale,2)}</td><td className={r.data.mae<r.data.baselineMae?'positive':'negative'}>{r.data.mae<r.data.baselineMae?'−':'+'}{fmt(Math.abs(r.data.mae/r.data.baselineMae-1)*100)}%</td></tr>)}</tbody></table></div><p className="footnote">MAE = average absolute error. Team RMSE: {fmt(report.team.report.rmse,2)} wins versus {fmt(report.team.report.baselineRmse,2)} for repeating last season. Player rates exclude target seasons with no appearances. Short seasons are normalized to 82 games.</p><div className="notice">The team model has slightly worse average absolute error than the baseline, despite lower RMSE. It is not a demonstrated across-the-board accuracy improvement.</div></section>
 <section className="panel"><h3>How much should you trust the range?</h3><p className="method-text">An 80% error band set from 2023 covered only {fmt(report.team.report.coverage80*100,0)}% of team outcomes, {fmt(report.minutes.report.coverage80*100,0)}% of playing-time outcomes, and {fmt(report.games.report.coverage80*100,0)}% of availability outcomes in 2024–2026. Those bands were too narrow. The dashboard uses broader held-out error scales, but its final probabilities have not been independently calibrated.</p><div className="notice">Player-data limitation: {report.cohort} The current cohort contains {report.players} roster entries, including players without usable history. Do not interpret these player scores as league-wide preseason accuracy.</div><p className="method-text">Each prediction uses prior-season statistics only; hyperparameters use 2023 only. Test outcomes do not select the fitted coefficients. The production model is then refitted through 2026. On/off, new-roster adjustments, manual scenarios, and the 2026–27 schedule are excluded from this historical component test.</p></section>
 <section className="panel"><h3>From historical rates to a future rotation</h3><ol className="method-list"><li><b>Fit playing time and availability separately.</b><p>Regularized regressions learn from the previous two seasons, prior games played, and age. You can override minutes, games, and roles in the rotation editor.</p></li><li><b>Learn production weights.</b><p>Each stat has its own fitted two-season weights and age interaction. Small samples shrink toward training-cohort per-minute averages; shrinkage strength is selected on 2023. Shooting percentages remain last season’s observed values.</p></li><li><b>Conserve opportunity.</b><p>Minutes × games ÷ 82 cannot exceed 240 across the team. Position minutes, unassigned minutes, and estimated shot volume reveal competition for opportunities. Usage and pace are explicit scenario assumptions, not learned causal effects.</p></li><li><b>Show the team context.</b><p>PBP Stats supplies observed pace and on/off usage for returning leaders where available. Off/on changes are shrunk and capped; they never silently extrapolate a tiny sample into a large boost.</p></li></ol></section>
 <section className="panel"><h3>One schedule. One winner per game.</h3><p className="method-text">The team baseline learns next-season wins from prior win percentage and two seasons of scoring margin. The current roster’s edited production changes the selected team’s projected scoring margin; the fitted margin coefficient maps that into strength. This roster translation is experimental and does not model defense or causal player value.</p><p className="method-text">Each run simulates all 30 teams together over {schedule.games.length.toLocaleString()} published games plus 30 balanced placeholders for unannounced matchups. Every team plays 82 games and total wins equal 1,230. There are 2,000 reproducible runs. Team-strength uncertainty uses historical errors; individual games use relative team strength. Home advantage, travel, rest, and playoff games are not modeled.</p><p className="method-text">The two unannounced games per team use fixed within-conference placeholders, not a forecast of NBA Cup qualification. Roster continuity widens the selected team’s uncertainty. Scenario probabilities remain experimental.</p><a className="source-link-inline" href={schedule.source} target="_blank" rel="noreferrer">Published ESPN schedule · snapshot {schedule.fetchedAt.slice(0,10)}</a></section>
 <section className="panel"><h3>Sources and freshness</h3><p className="method-text">ESPN supplies live current rosters and recent box-score averages; a dated snapshot is retained when refreshing fails. Model fitting, schedule, pace, and on/off are dated research snapshots from {report.trainedAt.slice(0,10)}. Refresh data updates ESPN roster/standings inputs only; it does not retrain the model.</p><div className="source-grid"><article><a href="https://site.api.espn.com/apis/v2/sports/basketball/nba/standings?season=2026&seasontype=2" target="_blank" rel="noreferrer">ESPN standings and team feeds</a><p>All 30 teams, 2015–2026 historical standings; player histories from 2015 where available.</p></article><article><a href={context.source} target="_blank" rel="noreferrer">PBP Stats pace and possessions</a><p>2025–26 regular season. On/off coverage is shown in the rotation editor with its source and samples.</p></article></div><p className="footnote">Free public sources can change or become unavailable. No paid projections, medical predictions, or guaranteed fantasy outcomes are represented.</p></section></div>;
}
